### ISSUE TITLE
Leftover po files ?

### ISSUE THREAD

**Issue by silopolis** [sphinx-doc/sphinx-doc-translations#16]
Hi,

Starting to work on the Internationalization page, a link to an XKCD page (always nice to found BTW ;) ), by luck at the top of it, made me realize I wasn't working on the good resource !
Quick search in Transifex editor showed me two resources: `intl` and `usage--advanced--intl`, and another one here in the repository that this may not be the only duplicate...
Looks like a bit of housekeeping is missing somewhere in the pipeline :)

**Comment by shimizukawa** [comment]
This repository holds a copy of the Transifex resources and is intended for use with the multilingual support of ReadTheDocs.

The two identical resources in Transifex may have occurred when the site structure was previously changed. I'll check it out.

**Comment by rffontenelle** [comment]
Issue solved in #38: obsolete resources in Transifex are now locked and after being 3 days are deleted, and obsolete PO and POT files are removed.
