### ISSUE TITLE
When will zh_TW be added in http://www.sphinx-doc.org/?

### ISSUE THREAD

**Issue by hwhsu1231** [sphinx-doc/sphinx-doc-translations#19]
A few weeks ago, I started to work on contributing zh_TW translation in Transifex.

And it seems that there is no string reviewed currently.

When will zh_TW be added in http://www.sphinx-doc.org/?

![image](https://github.com/sphinx-doc/sphinx-doc-translations/assets/71438617/17f11483-8194-4e3e-a131-b8c0a74731f6)
![image](https://github.com/sphinx-doc/sphinx-doc-translations/assets/71438617/5d606bdc-6bef-4e26-a060-61686a4ad9d4)

**Comment by AA-Turner** [comment]
@hwhsu1231 you need to add me as an admin on https://readthedocs.org/projects/sphinx-zh-tw/; then we can link it to the Sphinx docs.

A

**Comment by hwhsu1231** [comment]
@AA-Turner I added you.

![Screenshot_20231005-184241.png](https://github.com/sphinx-doc/sphinx-doc-translations/assets/71438617/701796de-14d3-46e4-95ed-71359ac704b6)

**Comment by AA-Turner** [comment]
Added.

A
