### ISSUE TITLE
Resources names as POT filename instead of the resource slug

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx-doc-translations#20]
Newly-added docs-related resources were created using POT filename as the resource name. That's a bug in sphinx-intl. Transifex organization admin, please fix the resource name to be equal to the resource slug, just like the rest of this project's resources.

| Resource name        | Resource slug                   |
|----------------------|---------------------------------|
| c.pot                | [usage--domains--c](https://app.transifex.com/sphinx-doc/sphinx-doc/usage--domains--c)               
| cpp.pot              | [usage--domains--cpp](https://app.transifex.com/sphinx-doc/sphinx-doc/usage--domains--cpp)
| index.pot            | [usage--domains--index](https://app.transifex.com/sphinx-doc/sphinx-doc/usage--domains--index)
| javascript.pot       | [usage--domains--javascript](https://app.transifex.com/sphinx-doc/sphinx-doc/usage--domains--javascript)
| mathematics.pot      | [usage--domains--mathematics](https://app.transifex.com/sphinx-doc/sphinx-doc/usage--domains--mathematics)
| python.pot           | [usage--domains--python](https://app.transifex.com/sphinx-doc/sphinx-doc/usage--domains--python)
| standard.pot         | [usage--domains--standard](https://app.transifex.com/sphinx-doc/sphinx-doc/usage--domains--standard)
| restructuredtext.pot | [usage--domains--restructuredtext](https://app.transifex.com/sphinx-doc/sphinx-doc/usage--domains--restructuredtext)

**Comment by AA-Turner** [comment]
> Transifex organization admin, please fix the resource name to be equal to the resource slug, just like the rest of this project's resources.

I'm a Transifex organization admin on https://www.transifex.com/sphinx-doc/. What should I do to fix this?

A

**Comment by rffontenelle** [comment]
Click each link > click on the right-side vertical ellipsis button > click Settings on the popup menu > Change "Name" content to the same as "Slug" content

**Comment by AA-Turner** [comment]
And remove the suffix (`.pot`)?

I've made you a 'team manager', not sure if that allows you to make the changes yourself (maybe a project maintainer?)

A

**Comment by rffontenelle** [comment]
To solve it permanently , https://github.com/sphinx-doc/sphinx-intl/pull/90 needs to land in the source code.

**Comment by rffontenelle** [comment]
> And remove the suffix (`.pot`)?
> 
> I've made you a 'team manager', not sure if that allows you to make the changes yourself (maybe a project maintainer?)
> 
> A

Let me check

**Comment by rffontenelle** [comment]
Correct. Now the name (under Recursos, that is Resources, in the image) is equal to the slug (in the URL bar):

![Captura de tela de 2023-10-03 15-03-43](https://github.com/sphinx-doc/sphinx-doc-translations/assets/1571783/849ae09a-2378-44b0-a397-6c4e66213fe4)

**Comment by rffontenelle** [comment]
I have no permission to do so. I just now because I compared with Python docs translation in Transifex, which I'm organization admin

**Comment by AA-Turner** [comment]
I made you a maintainer just now:

![image](https://github.com/sphinx-doc/sphinx-doc-translations/assets/9087854/ac1188e1-2c48-44b5-a1ed-53b15ee607e3)

**Comment by rffontenelle** [comment]
Ok, as Maintainer I can see it. Thanks.

**Comment by AA-Turner** [comment]
If anyone else wants to be a maintainer (& has a reasonable history/experience of translations) I am happy to add them.

A

**Comment by rffontenelle** [comment]
Resources names fixed. Thanks for the quick help with that.
