### ISSUE TITLE
Let us have custom placeholders in Transifex

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx-doc-translations#27]
It would really nice to have [custom placeholders](https://help.transifex.com/en/articles/6241794-setting-translation-checks) to ease [Sphinx documentation](https://app.transifex.com/sphinx-doc) translation.

Adding custom placeholders causes the matched expression to be highlighted, be assigned unique numbers in that string, and to be warned if translation differs from the source string. I use it a lot in Python docs translation in Transifex, and I highly recommend to Sphinx docs.

Example of placeholders set in Python docs:
![](https://i.imgur.com/av5PLmV.png)

Setting this requires:
- someone with organization admin role in Transifex, which I don't have and reason why I'm bringing this up.
- to find out every rst roles used in the documentation
- to set each placeholdler in Transifex, one by one

I might have found some commands to print the candidates for custom placeholders:

```shell
# Run this from this project root directory
# Generate 'strings.txt' with the whole-line of all translation strings
for pot in $(find locale/pot -name "*.pot"); do (msgcat --no-wrap $pot > tmp; mv tmp $pot;); done
grep -h ^msgid $(find locale/pot -name "*.pot") | sed 's|^msgid "||;s|"$||;/^$/d' > strings.txt
git checkout locale/

# Find roles with two parts like :c:macro:`something`.
grep -Po '(^|\s+):([\w\-\_\~]*:){2}`' strings.txt | sed -E 's|^ +||;' | sort -u

# Find roles with only one part like :doc:`something` 
grep -Po '(^|\s+):[\w\-\_\~]*:`' strings.txt | sed -E 's|^ +||;' | sort -u

# Take not of the command-line arguments like ``-j`` (but will not use this output)
grep -Po '``-[\w\s\-\_ ]*``' strings.txt

# Also a placeholder starting with `` and ending with `` should also be added

# Find project-specific variables like "|today|" (prints nothing, but let's leave this documented):
grep -Po '|[\w\_\-]*|' strings.txt
```

These commands will print these:

<details>
  <summary>Starting pattern for two-part roles (ending pattern is <code>`</code>)</summary>
  <pre>
$ grep -Po '(^|\s+):([\w\-\_\~]*:){2}`' strings.txt | sed -E 's|^ +||;' | sort -u
:c:macro:`
:cpp:expr:`
:cpp:type:`
:py:class:`
:py:data:`
:py:func:`
:py:meth:`
:py:mod:`
:py:obj:`
:rst:dir:`
:rst:role:`</pre>
</details>

<details>
  <summary>Starting pattern for one-part roles (ending pattern is <code>`</code>)</summary>
  <pre>
$ grep -Po '(^|\s+):([\w\-\_\~]*:)`' strings.txt | sed -E 's|^ +||;' | sort -u
:abbr:`
:attr:`
:class:`
:code:`
:command:`
:confval:`
:data:`
:dfn:`
:doc:`
:download:`
:dudir:`
:duref:`
:durole:`
:envvar:`
:event:`
:exc:`
:file:`
:func:`
:guilabel:`
:kbd:`
:literal:`
:mailheader:`
:makevar:`
:manpage:`
:math:`
:menuselection:`
:meth:`
:mimetype:`
:mod:`
:newsgroup:`
:obj:`
:option:`
:pep:`
:PEP:`
:program:`
:ref:`
:regexp:`
:rfc:`
:samp:`
:strong:`
:term:`</pre>
</details>

<details>
  <summary>Starting pattern for command-line arguments and literal text (ending pattern is <code>``</code>)</summary>
  <pre>
``--
``-
``
  </pre>
</details>

**Comment by AA-Turner** [comment]
Hi @rffontenelle I've made you an admininstrator.

A

**Comment by rffontenelle** [comment]
Done, added to placeholders to the Transifex organization's [PO translation validations](https://app.transifex.com/sphinx-doc/settings/validations/?drawer=PO#).

This applies both to Sphinx UI strings (`%r` and `{some-name}` were not considered placeholders until now) ...
![sphinx-ui](https://github.com/sphinx-doc/sphinx-doc-translations/assets/1571783/9eea5820-eeb8-4c98-96be-c9ce19ac625f)


... and sphinx documentation strings:
![image](https://github.com/sphinx-doc/sphinx-doc-translations/assets/1571783/f76e07ed-69b8-4f16-8abf-a6b02e05d626)

For roles that links to another page/website and are commonly translated, e.g. ```check :ref:`this website <http://example.com>`.```, I matched 1) fully the occurrence without space e.g. ```go to :ref:`html-options`.```, and 2) matched simply the role name when its content has space (see ref in the screenshot above)
