### ISSUE TITLE
Clean multiple Serbian teams in Transifex and readthedocs

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx-doc-translations#31]
It came to my attention that sphinx-doc organization in Transifex has 3 Serbian teams: [Serbian (sr)](https://app.transifex.com/sphinx-doc/teams/15434/sr/), [Serbian from Serbia (sr_RS)](https://app.transifex.com/sphinx-doc/teams/15434/sr_RS/) and [Serbian Latin](https://app.transifex.com/sphinx-doc/teams/36659/sr@latin/).

Regarding RTD projects there are only 2: [Serbian (sr)](https://readthedocs.org/projects/sphinx-sr/) and [Serbian from Serbia (sr_RS)](https://readthedocs.org/projects/sphinx-sr-rs/).

In the official docs website, there is only 1: [Serbian (sr)](http://www.sphinx-doc.org/sr). Serbian from Serbia (sr_RS)'s [sphinx-sr-rs.readthedocs.io](http://sphinx-sr-rs.readthedocs.io/) is redirected to [Serbian (sr)](http://www.sphinx-doc.org/sr).

Only the first one (sr) has more translations and all contributors from other teams are part of the first one.

**How about remove from Transifex the [Serbian from Serbia (sr_RS)](https://app.transifex.com/sphinx-doc/teams/15434/sr_RS/) and [Serbian Latin](https://app.transifex.com/sphinx-doc/teams/36659/sr@latin/) teams, and from Read the Docs the [Serbian from Serbia (sr_SR)](https://readthedocs.org/projects/sphinx-sr-rs/) ?**

Tasks:
- [x] Remove sr@latin and sr_RS from Transifex
- [x] Remove sr_RS from this repository
- [x] Remove readthedocs project

/cc @AA-Turner

**Comment by AA-Turner** [comment]
Seems reasonable!

A

**Comment by rffontenelle** [comment]
@AA-Turner  or @shimizukawa, would either one of you remove https://readthedocs.org/projects/sphinx-sr-rs/? After that, sr_RS is over.

Please notice I tried to contact all translators from all Serbian language teams, but received no contact. Therefore, I went ahead and removed it.

**Comment by shimizukawa** [comment]
OK, I'll remove it

**Comment by shimizukawa** [comment]
Done. 
![Screenshot_20240211-083853.png](https://github.com/sphinx-doc/sphinx-doc-translations/assets/151623/90269270-b036-479f-a825-a80ae6cd210d)

**Comment by rffontenelle** [comment]
Thanks for your help on this matter
