### ISSUE TITLE
pt_BR and zh_CN: Documentation is built in English because RTD is unable to find PO files

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx-doc-translations#35]
[.readthedocs.yml](https://github.com/sphinx-doc/sphinx-doc-translations/blob/7aad1bbad523a4302895727d47f808d7437a9961/.readthedocs.yml) sets `-D language=$READTHEDOCS_LANGUAGE` and the environment variable $READTHEDOCS_LANGUAGE in  Read The Docs gives `pt-br` and `zh-cn` (all lowercase, dash instead of underscore). This causes the docs build to not find the translation files (since there is a pt_BR/ directory, not a pt-br/).

One solution is to map the language codes so that pt_BR in Transifex is downloaded as pt-br, etc.  Another solution is to convert pt_BR -> pt-br when running in readthedocs

**Comment by rffontenelle** [comment]
@AA-Turner Could you please [configure pull request builds](https://docs.readthedocs.io/en/stable/guides/pull-requests.html) in [sphinx-pt-br](https://readthedocs.org/projects/sphinx-pt-br/) project at Read the Docs? I would like to test mapping language & renaming directory pt_BR to pt-br in a pull request, and I this preview build would be very handy

**Comment by AA-Turner** [comment]
I tried to add you but ``rffontenelle`` isn't a user on RTD.

A

**Comment by rffontenelle** [comment]
> I tried to add you but ``rffontenelle`` isn't a user on RTD.
> 
> A

`rafaelff` is my username in RTD.

**Comment by rffontenelle** [comment]
https://blog.readthedocs.com/language-codes-are-now-normalized/

> The following language codes are now normalized to be lowercase and use a dash as a separator instead of an underscore:
> pt_BR is now pt-br
> zh_CN is now zh-cn
