### ISSUE TITLE
English not listed in language picker when browsing translated docs

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx-doc-translations#46]
Steps to reproduce:

1- Browse an English page, e.g. https://www.sphinx-doc.org/en/master/index.html
2- Note that the language picker shows all languages available, 'en' included
3- Select any other language
4- Check the language picker again, and English 'en' is not listed anymore

**Comment by humitos** [comment]
The flyout show the "English" `en` version to me following those steps.

![Screenshot_2024-06-12_12-07-55](https://github.com/sphinx-doc/sphinx-doc-translations/assets/244656/ddd8bc33-e7d7-4ee2-acc0-a0907c85dd2f)
