### ISSUE TITLE
Read The Docs dialog shown in English in translated docs

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx-doc-translations#48]
| English Sphinx documentation | Translated (pt-br) Sphinx documentation |
| --------------------------------------------------------- | ----------------------------------------------------------------------- |
| ![image](https://github.com/sphinx-doc/sphinx-doc-translations/assets/1571783/876bafc7-1276-4f4f-b986-4252876d59d6) | ![image](https://github.com/sphinx-doc/sphinx-doc-translations/assets/1571783/b377e8a1-3b12-49b3-abb2-5da72c6c09ee)

Both output from a system set with Brazilian Portuguese locale.

Maybe this is related to the fact that we are using RTD's [build.commands](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-commands) config in the [.readthedocs.yml](https://github.com/sphinx-doc/sphinx-doc-translations/blob/ac68470b54d79b38d6edce9271f4d1b727d623c1/.readthedocs.yml) file... ?

**Comment by humitos** [comment]
The flyout version from the left is the old deprecated version. The one from the right is the new version (Read the Docs Addons). Unfortunately, it's not translated yet. We have an issue at https://github.com/readthedocs/addons/issues/12 to track this work, but we haven't had the time to jump into it yet.

> Maybe this is related to the fact that we are using RTD's `build.commands`

Note that when using `build.commands`, Read the Docs Addons is enabled automatically. In the near future, _all_ builds will always use the new Read the Docs Addons and the old flyout version will be removed.

**Comment by rffontenelle** [comment]
Great, thanks for the info. I subscribed to follow evolution of that issue. Looks like there is nothing to do from our side then, so I'll be closing this.
