### ISSUE TITLE
Translation pattern on Read the Docs

### ISSUE THREAD

**Issue by humitos** [sphinx-doc/sphinx-doc-translations#53]
Hi 👋🏼 all.

I'm opening this issue here because I found the following note in the README file:

> The current procedure is bit tricky because Read The Docs doesn't have a way to specify options for sphinx-build command. conf.py files for each languages have language and locale_dirs values without having full copy of conf.py of sphinx doc. If we want to specify conf.py file that is out of source directory, we will use -c option for the sphinx-build command. Unfortunately Read the Docs doesn't support that. If there is a better way, open an issue.

I'm not sure _when_ you setup the translations for Sphinx, but it may happened that Read the Docs has changed since then. There are a few different ways you can setup the translation without these limitations anymore. Oh, by the way, I'm a Read the Docs maintainer 😅 

## Following your _current_ pattern

_It's worth to mention that I don't exactly know what's your current pattern, and I'm just mentioning the solution to the limitation from the quoted text_

You can use [`sphinx.configuration`](https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-configuration) YAML config in your `.readthedocs.yaml` file to specify a Sphinx's `conf.py` file.

Also, you can use [`build.commands`](https://docs.readthedocs.io/en/latest/build-customization.html) YAML config if you want to declare _all the commands_ you want to run in the build process.

## Following a pattern _similar_ to what CPython does [^1]

CPython has a _main_ repository at https://github.com/python/cpython/ and then one repository for each translation (e.g. Spanish translation at https://github.com/python/python-docs-es/) which includes _only the .po_ files.

Then, when building the Spanish translation, the _main_ repository is cloned together with the Spanish repository at `Doc/locale/es/LC_MESSAGES` and then run the `sphinx-build` command with `language=es`.

You can see [this build](https://app.readthedocs.org/projects/cpython-previews-es/builds/25042115/) as an example for the CPython Spanish translation and its corresponding custom [`.readthedocs.yaml`](https://github.com/readthedocs/cpython/blob/main/Doc/locales/es/.readthedocs.yaml) file for the translation.

----

Let me know if this information is useful and if you have any question.

[^1]: they are not building their documentation/translations on Read the Docs yet, but we setup the process to showcase how it would be when the migration is done.

**Comment by rffontenelle** [comment]
This doc is out-of-date after #49, where I replaced several manual statements in `build.commands` (that required specifying a lot of stuff, but wouldn't allow installing APT packages) with a more RTD-ish YAML file using `build.apt_packages`, `submodules`, `formats`, and `python.install`.

TODO: update doc.

**Comment by rffontenelle** [comment]
Fixed in [727fdae](https://github.com/sphinx-doc/sphinx-doc-translations/commit/727fdae494fc7ff857e8a2218bc9ae2b28822e4f)
