### ISSUE TITLE
Some Chinese translations confused me

### ISSUE THREAD

**Issue by Zeroto521** [sphinx-doc/sphinx-doc-translations#8]
I came from [sphinx doc, autosummary section](https://www.sphinx-doc.org/zh_CN/master/usage/extensions/autosummary.html).

Some translation results confused me. Like following one.

Chinese result:

```
：文件：`autosummary/基准.rst`
```

English source:

```
:file:`autosummary/base.rst`
```

I thought `:file:` is a mark and `base.rst` is a specific file name, it shouldn't translate.
If they were translated, they couldn't be understood well.
So just keep the origin is fine, like this.

```
":file:`autosummary/base.rst` -- 回退模板" 
```

And I found there have the same problems in other places.

https://github.com/sphinx-doc/sphinx-doc-translations/blob/a4fc81bbed422f2139a23ead81913c284f96afad/locale/zh_CN/LC_MESSAGES/usage/extensions/autosummary.po#L304-L326

**Comment by shimizukawa** [comment]
Thanks for your reporting!

However sphinx translation catalogs are managed on Transifex service.
Can you update them directry?
https://www.transifex.com/sphinx-doc/sphinx-doc/dashboard/

**Comment by Zeroto521** [comment]
I have done these and also fixed some other problems.

> Thanks for your reporting!
> 
> However sphinx translation catalogs are managed on Transifex service.
> Can you update them directry?
> https://www.transifex.com/sphinx-doc/sphinx-doc/dashboard/
