### ISSUE TITLE
travis-ci.org builds ceased; go to travis-ci.com 

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx-doc-translations#9]
I see the .travis-ci.yml pointing to [travis-ci.org], which is no longer working. From [sphinx-doc-translations project on travis-ci.org]:

> Since June 15th, 2021, the building on [travis-ci.org] is ceased. Please use [travis-ci.com] from now on.

On travis-ci.com, the [sphinx-doc-translations project] has empty build history as well.

I see a pending PR on migrating travis to GitHub Actions, but how about fixing it while the PR doesn't land?

[travis-ci.org]: https://travis-ci.org
[travis-ci.com]: https://travis-ci.com
[sphinx-doc-translations project on travis-ci.org]: https://travis-ci.org/github/sphinx-doc/sphinx-doc-translations
[sphinx-doc-translations project]: https://app.travis-ci.com/github/sphinx-doc/sphinx-doc-translations/builds

**Comment by shimizukawa** [comment]
ok, I'm going  to migrate CI to GitHub Actions.

**Comment by shimizukawa** [comment]
Done!
https://github.com/sphinx-doc/sphinx-doc-translations/pull/12
